/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:a90d3606-8f79-426f-a755-55ec4d1c71be",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_bwwK5pgfD",
    "aws_user_pools_web_client_id": "17oiia7eb23gtks7ievini2f7i",
    "oauth": {}
};


export default awsmobile;
